# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 320)
        Form.setMinimumSize(QtCore.QSize(600, 320))
        Form.setMaximumSize(QtCore.QSize(600, 300))
        Form.setStyleSheet("background-color: rgb(22, 29, 32);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(Form)
        self.header.setMaximumSize(QtCore.QSize(16777215, 60))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_header = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setStyleSheet("color:rgb(255, 255, 255);")
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.horizontalLayout.addWidget(self.lbl_header)
        self.verticalLayout.addWidget(self.header)
        self.body = QtWidgets.QFrame(Form)
        self.body.setMaximumSize(QtCore.QSize(600, 16777215))
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.message = QtWidgets.QFrame(self.body)
        self.message.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message.setObjectName("message")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.message)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_msg = QtWidgets.QLabel(self.message)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.lbl_msg.setFont(font)
        self.lbl_msg.setStyleSheet("color:rgb(255, 255, 255)")
        self.lbl_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_msg.setObjectName("lbl_msg")
        self.horizontalLayout_3.addWidget(self.lbl_msg)
        self.lbl_msg.raise_()
        self.verticalLayout_2.addWidget(self.message)
        self.buttons = QtWidgets.QFrame(self.body)
        self.buttons.setMaximumSize(QtCore.QSize(16777215, 90))
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel = QtWidgets.QPushButton(self.buttons)
        self.cancel.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(45,45,45);\n"
"    border:2px solid rgb(20, 244, 255);\n"
"    color:rgb(30,211,231)\n"
"}")
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.confirm = QtWidgets.QPushButton(self.buttons)
        self.confirm.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:rgb(45,45,45);\n"
"    border:2px solid rgb(20, 244, 255);\n"
"    color:rgb(30,211,231)\n"
"}")
        self.confirm.setObjectName("confirm")
        self.horizontalLayout_2.addWidget(self.confirm)
        self.verticalLayout_2.addWidget(self.buttons)
        self.verticalLayout.addWidget(self.body)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_header.setText(_translate("Form", "Confirm Vote"))
        self.lbl_msg.setText(_translate("Form", "You select\n"
"candidate 1\n"
"confirm your vote"))
        self.cancel.setText(_translate("Form", "Cancel"))
        self.confirm.setText(_translate("Form", "Confirm"))
