# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smartPoll.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import fin
from voterDetails import voters
from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import json


class Ui_MainWindow(object):

    isStartedVoting = False
    isAuthenticated = False
    selectedVoter = ""

    def call_fingerPRint(self):
        self.lbl_message.setText("Reading finger print...")
        self.read_fingerPrint()

    def read_fingerPrint(self):
        if fin.get_fingerprint():
            voter = fin.findVoter(fin.finger.finger_id)
            print("Voter's fingerprint Authenticatd")
            isAuthenticacted = True
            self.verify.setText("Let Start Voting")
            self.lbl_message.setText(
                f'Authenticated user\nNIC : {voter["nic"]}')
            self.isStartedVoting = True
            self.verify.hide()
            self.start_vote.show()
            self.exit.show()

            print(voter)
        else:
            print("Voter not recognized. Try again\n")
            self.lbl_message.setText(
                "Cannot Authenticate.\nplease contact Admin.")
            self.verify.hide()
            self.exit.show()

    def start_voting(self):
        if (self.isStartedVoting):
            self.buttons.hide()
            self.message.hide()
            self.candidates.show()
            self.lbl_header.setText("Choose Your Vote")

    def set_vote(self):
        print("called")
        data = {
            "party": self.selectedVoter,
            "divisionID": "63b534f2cb9215bec19ea92f"
        }

        shared_obj = json.dumps(data, indent=4)

        header = {'Content-Type': 'application/json'}
        response = requests.post(
            "http://3.93.242.30:4000/votes/add", data=shared_obj, headers=header)

        print(response.content)

        self.lbl_header.setText(".smart poll")
        self.candidates.hide()
        self.message.show()
        self.lbl_message.setText(
            f'Your vote is given to\n{self.selectedVoter}.')
        self.lbl_message2.hide()
        self.buttons.show()
        self.confirm.hide()
        self.exit.setText("Finish")
        self.exit.show()
        self.start_vote.hide()

    def confirm_vote(self, vote):
        self.selectedVoter = vote
        self.exit.hide()
        self.confirm.show()
        self.lbl_header.setText("Confirm Vote")
        self.candidates.hide()
        self.message.show()
        self.lbl_message.setText(
            f'Your vote is given to\n{self.selectedVoter}.')
        self.lbl_message2.setText("confirm your vote to record the vote")
        self.lbl_message2.show()
        self.buttons.show()
        self.start_vote.setText("Choose Again")
        self.start_vote.show()

    def initialize(self):
        self.start_vote.hide()
        self.exit.setText("Exit")
        self.exit.hide()
        self.confirm.hide()
        self.verify.setText("Verify My Authentication")
        self.start_vote.setText("Let Start Voting")
        self.verify.show()
        self.candidates.hide()
        self.lbl_message2.hide()
        self.lbl_message.setText("Hi There,\nWelcome to the Smart Poll")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.body = QtWidgets.QFrame(self.centralwidget)
        self.body.setGeometry(QtCore.QRect(0, 100, 800, 380))
        self.body.setMinimumSize(QtCore.QSize(800, 380))
        self.body.setMaximumSize(QtCore.QSize(16777215, 380))
        self.body.setStyleSheet("")
        self.body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body.setObjectName("body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message = QtWidgets.QFrame(self.body)
        self.message.setMaximumSize(QtCore.QSize(16777214, 1000))
        self.message.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.message.setObjectName("message")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.message)
        self.verticalLayout_2.setContentsMargins(100, -1, 100, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_message = QtWidgets.QLabel(self.message)
        self.lbl_message.setMaximumSize(QtCore.QSize(600, 3213123))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_message.setFont(font)
        self.lbl_message.setStyleSheet("color: rgb(255, 255, 255);")
        self.lbl_message.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_message.setObjectName("lbl_message")
        self.verticalLayout_2.addWidget(self.lbl_message)
        self.lbl_message2 = QtWidgets.QLabel(self.message)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_message2.setFont(font)
        self.lbl_message2.setStyleSheet("color:rgb(255, 255, 255)")
        self.lbl_message2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_message2.setObjectName("lbl_message2")
        self.verticalLayout_2.addWidget(self.lbl_message2)
        self.verticalLayout.addWidget(self.message)
        self.candidates = QtWidgets.QFrame(self.body)
        self.candidates.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.candidates.setFrameShadow(QtWidgets.QFrame.Raised)
        self.candidates.setObjectName("candidates")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.candidates)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.scrollArea = QtWidgets.QScrollArea(self.candidates)
        self.scrollArea.setMinimumSize(QtCore.QSize(670, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(670, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 651, 684))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c1 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.c1.setMinimumSize(QtCore.QSize(630, 90))
        self.c1.setMaximumSize(QtCore.QSize(630, 90))
        self.c1.setStyleSheet("border-bottom:1px solid rgb(20, 20, 20);")
        self.c1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c1.setObjectName("c1")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.c1)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.b1 = QtWidgets.QPushButton(self.c1)
        self.b1.setMinimumSize(QtCore.QSize(550, 0))
        self.b1.setMaximumSize(QtCore.QSize(550, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setStyleSheet("QPushButton {\n"
                              "    border:0;\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    border-radius:10px;\n"
                              "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed{\n"
                              "    background-color:rgb(45,45,45);\n"
                              "    border:2px solid rgb(20, 244, 255);\n"
                              "    color:rgb(30,211,231)\n"
                              "}")
        self.b1.setObjectName("b1")
        self.horizontalLayout_19.addWidget(self.b1)
        self.verticalLayout_3.addWidget(self.c1)
        self.c2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.c2.setMinimumSize(QtCore.QSize(630, 90))
        self.c2.setMaximumSize(QtCore.QSize(630, 90))
        self.c2.setStyleSheet("border-bottom:1px solid rgb(20, 20, 20);")
        self.c2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c2.setObjectName("c2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.c2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.b2 = QtWidgets.QPushButton(self.c2)
        self.b2.setMinimumSize(QtCore.QSize(550, 0))
        self.b2.setMaximumSize(QtCore.QSize(550, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setStyleSheet("QPushButton {\n"
                              "    border:0;\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    border-radius:10px;\n"
                              "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed{\n"
                              "    background-color:rgb(45,45,45);\n"
                              "    border:2px solid rgb(20, 244, 255);\n"
                              "    color:rgb(30,211,231)\n"
                              "}")
        self.b2.setObjectName("b2")
        self.horizontalLayout_18.addWidget(self.b2)
        self.verticalLayout_3.addWidget(self.c2)
        self.c3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.c3.setMinimumSize(QtCore.QSize(630, 90))
        self.c3.setMaximumSize(QtCore.QSize(630, 90))
        self.c3.setStyleSheet("border-bottom:1px solid rgb(20, 20, 20);")
        self.c3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c3.setObjectName("c3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.c3)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.b3 = QtWidgets.QPushButton(self.c3)
        self.b3.setMinimumSize(QtCore.QSize(550, 0))
        self.b3.setMaximumSize(QtCore.QSize(550, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setStyleSheet("QPushButton {\n"
                              "    border:0;\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    border-radius:10px;\n"
                              "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed{\n"
                              "    background-color:rgb(45,45,45);\n"
                              "    border:2px solid rgb(20, 244, 255);\n"
                              "    color:rgb(30,211,231)\n"
                              "}")
        self.b3.setObjectName("b3")
        self.horizontalLayout_17.addWidget(self.b3)
        self.verticalLayout_3.addWidget(self.c3)
        self.c4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.c4.setMinimumSize(QtCore.QSize(630, 90))
        self.c4.setMaximumSize(QtCore.QSize(630, 90))
        self.c4.setStyleSheet("border-bottom:1px solid rgb(20, 20, 20);")
        self.c4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c4.setObjectName("c4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.c4)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.b4 = QtWidgets.QPushButton(self.c4)
        self.b4.setMinimumSize(QtCore.QSize(550, 0))
        self.b4.setMaximumSize(QtCore.QSize(550, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setStyleSheet("QPushButton {\n"
                              "    border:0;\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    border-radius:10px;\n"
                              "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed{\n"
                              "    background-color:rgb(45,45,45);\n"
                              "    border:2px solid rgb(20, 244, 255);\n"
                              "    color:rgb(30,211,231)\n"
                              "}")
        self.b4.setObjectName("b4")
        self.horizontalLayout_16.addWidget(self.b4)
        self.verticalLayout_3.addWidget(self.c4)
        self.c5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.c5.setMinimumSize(QtCore.QSize(630, 90))
        self.c5.setMaximumSize(QtCore.QSize(630, 90))
        self.c5.setStyleSheet("border-bottom:1px solid rgb(20, 20, 20);")
        self.c5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c5.setObjectName("c5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.c5)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.b5 = QtWidgets.QPushButton(self.c5)
        self.b5.setMinimumSize(QtCore.QSize(550, 0))
        self.b5.setMaximumSize(QtCore.QSize(550, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setStyleSheet("QPushButton {\n"
                              "    border:0;\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    border-radius:10px;\n"
                              "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed{\n"
                              "    background-color:rgb(45,45,45);\n"
                              "    border:2px solid rgb(20, 244, 255);\n"
                              "    color:rgb(30,211,231)\n"
                              "}")
        self.b5.setObjectName("b5")
        self.horizontalLayout_15.addWidget(self.b5)
        self.verticalLayout_3.addWidget(self.c5)
        self.c6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.c6.setMinimumSize(QtCore.QSize(630, 90))
        self.c6.setMaximumSize(QtCore.QSize(630, 90))
        self.c6.setStyleSheet("border-bottom:1px solid rgb(20, 20, 20);")
        self.c6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c6.setObjectName("c6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.c6)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.b6 = QtWidgets.QPushButton(self.c6)
        self.b6.setMinimumSize(QtCore.QSize(550, 0))
        self.b6.setMaximumSize(QtCore.QSize(550, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setStyleSheet("QPushButton {\n"
                              "    border:0;\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    border-radius:10px;\n"
                              "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed{\n"
                              "    background-color:rgb(45,45,45);\n"
                              "    border:2px solid rgb(20, 244, 255);\n"
                              "    color:rgb(30,211,231)\n"
                              "}")
        self.b6.setObjectName("b6")
        self.horizontalLayout_12.addWidget(self.b6)
        self.verticalLayout_3.addWidget(self.c6)
        self.c7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.c7.setMinimumSize(QtCore.QSize(630, 90))
        self.c7.setMaximumSize(QtCore.QSize(630, 90))
        self.c7.setStyleSheet("border-bottom:1px solid rgb(20, 20, 20);")
        self.c7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.c7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.c7.setObjectName("c7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.c7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b7 = QtWidgets.QPushButton(self.c7)
        self.b7.setMinimumSize(QtCore.QSize(550, 0))
        self.b7.setMaximumSize(QtCore.QSize(550, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setStyleSheet("QPushButton {\n"
                              "    border:0;\n"
                              "    color: rgb(255, 255, 255);\n"
                              "    border-radius:10px;\n"
                              "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed{\n"
                              "    background-color:rgb(45,45,45);\n"
                              "    border:2px solid rgb(20, 244, 255);\n"
                              "    color:rgb(30,211,231)\n"
                              "}")
        self.b7.setObjectName("b7")
        self.horizontalLayout_3.addWidget(self.b7)
        self.verticalLayout_3.addWidget(self.c7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_14.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.candidates)
        self.buttons = QtWidgets.QFrame(self.body)
        self.buttons.setMaximumSize(QtCore.QSize(16777215, 80))
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verify = QtWidgets.QPushButton(self.buttons)
        self.verify.setMaximumSize(QtCore.QSize(290, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.verify.setFont(font)
        self.verify.setStyleSheet("QPushButton {\n"
                                  "    color: rgb(255, 255, 255);\n"
                                  "    border-radius:5px;\n"
                                  "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed{\n"
                                  "    background-color:rgb(45,45,45);\n"
                                  "    border:2px solid rgb(20, 244, 255);\n"
                                  "    color:rgb(30,211,231)\n"
                                  "}")
        self.verify.setObjectName("verify")
        self.horizontalLayout.addWidget(self.verify)
        self.start_vote = QtWidgets.QPushButton(self.buttons)
        self.start_vote.setMaximumSize(QtCore.QSize(290, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.start_vote.setFont(font)
        self.start_vote.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    border-radius:5px;\n"
                                      "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed{\n"
                                      "    background-color:rgb(45,45,45);\n"
                                      "    border:2px solid rgb(20, 244, 255);\n"
                                      "    color:rgb(30,211,231)\n"
                                      "}")
        self.start_vote.setObjectName("start_vote")
        self.horizontalLayout.addWidget(self.start_vote)
        self.exit = QtWidgets.QPushButton(self.buttons)
        self.exit.setMaximumSize(QtCore.QSize(290, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton {\n"
                                "    color: rgb(255, 255, 255);\n"
                                "    border-radius:5px;\n"
                                "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed{\n"
                                "    background-color:rgb(45,45,45);\n"
                                "    border:2px solid rgb(20, 244, 255);\n"
                                "    color:rgb(30,211,231)\n"
                                "}")
        self.exit.setObjectName("exit")
        self.horizontalLayout.addWidget(self.exit)
        self.confirm = QtWidgets.QPushButton(self.buttons)
        self.confirm.setMaximumSize(QtCore.QSize(290, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("QPushButton {\n"
                                   "    color: rgb(255, 255, 255);\n"
                                   "    border-radius:5px;\n"
                                   "    background-color: qlineargradient(spread:repeat, x1:0, y1:1, x2:0.932, y2:0, stop:0 rgba(51, 99, 131, 255), stop:0.272727 rgba(51, 99, 131, 255), stop:0.818182 rgba(33, 150, 173, 255));\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed{\n"
                                   "    background-color:rgb(45,45,45);\n"
                                   "    border:2px solid rgb(20, 244, 255);\n"
                                   "    color:rgb(30,211,231)\n"
                                   "}")
        self.confirm.setObjectName("confirm")
        self.horizontalLayout.addWidget(self.confirm)
        self.verticalLayout.addWidget(self.buttons)
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(0, 0, 800, 90))
        self.header.setMinimumSize(QtCore.QSize(800, 90))
        self.header.setMaximumSize(QtCore.QSize(800, 90))
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_header = QtWidgets.QLabel(self.header)
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setStyleSheet("color:rgb(255, 255, 255)")
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.horizontalLayout_13.addWidget(self.lbl_header)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_message.setText(_translate("MainWindow", "Hi There,\n"
                                            "Welcome to the Smart Poll"))
        self.lbl_message2.setText(_translate("MainWindow", "TextLabel"))
        self.b1.setText(_translate("MainWindow", "MR. Candidate 1"))
        self.b2.setText(_translate("MainWindow", "MR. Candidate 2"))
        self.b3.setText(_translate("MainWindow", "MR. Candidate 3"))
        self.b4.setText(_translate("MainWindow", "MR. Candidate 4"))
        self.b5.setText(_translate("MainWindow", "MR. Candidate 5"))
        self.b6.setText(_translate("MainWindow", "MR. Candidate 6"))
        self.b7.setText(_translate("MainWindow", "MR. Candidate 7"))
        self.verify.setText(_translate(
            "MainWindow", "Verify My Authentication"))
        self.start_vote.setText(_translate("MainWindow", "Let Start Voting"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.confirm.setText(_translate("MainWindow", "Confirm"))
        self.lbl_header.setText(_translate("MainWindow", ".smart poll"))

        self.verify.clicked.connect(self.call_fingerPRint)
        self.start_vote.clicked.connect(self.start_voting)
        self.b1.clicked.connect(lambda: self.confirm_vote(self.b1.text()))
        self.b2.clicked.connect(lambda: self.confirm_vote(self.b2.text()))
        self.b3.clicked.connect(lambda: self.confirm_vote(self.b3.text()))
        self.b4.clicked.connect(lambda: self.confirm_vote(self.b4.text()))
        self.b5.clicked.connect(lambda: self.confirm_vote(self.b5.text()))
        self.b6.clicked.connect(lambda: self.confirm_vote(self.b6.text()))
        self.b7.clicked.connect(lambda: self.confirm_vote(self.b7.text()))
        self.exit.clicked.connect(self.initialize)
        self.confirm.clicked.connect(self.set_vote)
