const mongoose = require("mongoose");
const Province = require("./province");

const districtSchema = new mongoose.Schema({
  provinceID: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Province",
  },
  name: {
    type: String,
    required: true,
    unique: true,
    enum: [
      "Matara",
      "Galle",
      "Hambantota",
      "Kalutara",
      "Colombo",
      "Kegalle",
      "Kandy",
      "Matale",
      "Anuradhapura",
      "Polonnaruwa",
      "Vauniya",
      "Madakalauwa",
      "Ampara",
      "Gampaha",
      "Nuwara Eliya",
      "Jaffna",
      "Mannar",
      "Mulathiv",
      "Kilinochchi",
      "Batticaloa",
      "Trincomalee",
      "Kurunagala",
      "Puttalam",
      "Badulla",
      "Monaragala",
      "Rathnapura",
    ],
  },
  voterCount: {
    type: Number,
    required: true,
  },
  districtID: {
    type: String,
    required: true,
    unique: true,
    enum: [
      "D-01",
      "D02",
      "D-03",
      "D-04",
      "D-05",
      "D-06",
      "D-07",
      "D-08",
      "D-09",
      "D-10",
      "D-11",
      "D-12",
      "D-13",
      "D-14",
      "D-15",
      "D-16",
      "D-17",
      "D-18",
      "D-19",
      "D-20",
      "D-21",
      "D-22",
      "D-23",
      "D-24",
      "D-25",
    ],
  },
});

const Division = mongoose.model("Division", districtSchema);

exports.Voter = Division;
