const mongoose = require("mongoose");
const District = require("./district");
const Province = require("./province");
// const Fawn = require("fawn");
// Fawn.init(mongoose);

const divisionSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    unique: true,
    enum: ["Akurana"
          ,"Delthota"
          ,"Doluwa"
          ,"Gagawata Korale"
          ,"Ganga Ihala Korale"
          ,"Harispattuwa"
          ,"Hatharaliyadda"
          ,"Kundasale"
          ,"Medadumbara"
          ,"Minipe"
          ,"Panvila"
          ,"Pasbage Korale"
          ,"Pathadumbara"
          ,"Pathahewaheta"
          ,"Poojapitiya"
          ,"Thumpane"
          ,"Udadumbara"
          ,"Udapalatha"
          ,"Udunuwara"
          ,"Yatinuwara"
          ,"Ambanganga Korale"
          ,"Dambulla"
          ,"Galewela"
          ,"Laggala-Pallegama"
          ,"Matale"
          ,"Naula"
          ,"Pallepola"
          ,"Rattota"
          ,"Ukuwela"
          ,"Wilgamuwa"
          ,"Yatawatta"
          ,"Ambagamuwa"
          ,"Hanguranketha"
          ,"Kothmale"
          ,"Nuwara Eliya"
          ,"Walapane"
          ,"Addalachchenai"
          ,"Akkaraipattu"
          ,"Alayadiwembu"
          ,"Ampara"
          ,"Damana"
          ,"Dehiattakandiya"
          ,"Eragama"
          ,"Kalmunai Muslim"
          ,"Kalmunai Tamil"
          ,"Karaitivu"
          ,"Lahugala"
          ,"Mahaoya"
          ,"Navithanveli"
          ,"Ninthavur"
          ,"Padiyathalawa"
          ,"Pothuvil"
          ,"Sainthamarathu"
          ,"Samanthurai"
          ,"Thirukkovil"
          ,"Uhana"
          ,"Eravur Pattu"
          ,"Eravur Town"
          ,"Kattankudy"
          ,"Koralai Pattu"
          ,"Koralai Pattu Central"
          ,"Koralai Pattu North"
          ,"Koralai Pattu South"
          ,"Koralai Pattu West"
          ,"Manmunai North"
          ,"Manmunai Pattu"
          ,"Manmunai S. and Eruvil Pattu"
          ,"Manmunai South West"
          ,"Manmunai West"
          ,"Porativu Pattu"
          ,"Gomarankadawala"
          ,"Kantalai"
          ,"Kinniya"
          ,"Kuchchaveli"
          ,"Morawewa"
          ,"Muttur"
          ,"Padavi Sri Pura"
          ,"Seruvila"
          ,"Thambalagamuwa"
          ,"Trincomalee"
          ,"Verugal"
          ,"Galnewa"
          ,"Galenbindunuwewa"
          ,"Horowpothana"
          ,"Ipalogama"
          ,"Kahatagasdigiliya"
          ,"Kebithigollewa"
          ,"Kekirawa"
          ,"Mahavilachchiya"
          ,"Medawachchiya"
          ,"Mihinthale"
          ,"Nachchadoowa"
          ,"Nochchiyagama"
          ,"Nuwaragam Palatha Central"
          ,"Nuwaragam Palatha East"
          ,"Padaviya"
          ,"Palagala"
          ,"Palugaswewa"
          ,"Rajanganaya"
          ,"Rambewa"
          ,"Thalawa"
          ,"Thambuttegama"
          ,"Thirappane"
          ,"Dimbulagala"
          ,"Elahera"
          ,"Hingurakgoda"
          ,"Lankapura"
          ,"Medirigiriya"
          ,"Thamankaduwa"
          ,"Welikanda"
          ,"Delft"
          ,"Island North"
          ,"Island South"
          ,"Jaffna"
          ,"Karainagar"
          ,"Nallur"
          ,"Thenmaradchi"
          ,"Vadamaradchi East"
          ,"Vadamaradchi North"
          ,"Vadamaradchi South-West"
          ,"Valikamam East"
          ,"Valikamam North"
          ,"Valikamam South"
          ,"Valikamam South-West"
          ,"Valikamam West"
          ,"Kandavalai"
          ,"Karachchi"
          ,"Pachchilaipalli"
          ,"Poonakary"
          ,"Madhu"
          ,"Mannar"
          ,"Manthai West"
          ,"Musalai"
          ,"Nanaddan"
          ,"Manthai East"
          ,"Maritimepattu"
          ,"Oddusuddan"
          ,"Puthukudiyiruppu"
          ,"Thunukkai"
          ,"Welioya"
          ,"Vavuniya"
          ,"Vavuniya North"
          ,"Vavuniya South"
          ,"Vengalacheddikulam"
          ,"Alawwa"
          ,"Ambanpola"
          ,"Bamunakotuwa"
          ,"Bingiriya"
          ,"Ehetuwewa"
          ,"Galgamuwa"
          ,"Ganewatta"
          ,"Giribawa"
          ,"Ibbagamuwa"
          ,"Katupotha"
          ,"Kobeigane"
          ,"Kotavehera"
          ,"Kuliyapitiya East"
          ,"Kuliyapitiya West"
          ,"Kurunegala"
          ,"Mahawa"
          ,"Mallawapitiya"
          ,"Maspotha"
          ,"Mawathagama"
          ,"Narammala"
          ,"Nikaweratiya"
          ,"Panduwasnuwara"
          ,"Pannala"
          ,"Polgahawela"
          ,"Polpithigama"
          ,"Rasnayakapura"
          ,"Rideegama"
          ,"Udubaddawa"
          ,"Wariyapola"
          ,"Weerambugedara"
          ,"Anamaduwa"
          ,"Arachchikattuwa"
          ,"Chilaw"
          ,"Dankotuwa"
          ,"Kalpitiya"
          ,"Karuwalagaswewa"
          ,"Madampe"
          ,"Mahakumbukkadawala"
          ,"Mahawewa"
          ,"Mundalama"
          ,"Nattandiya"
          ,"Nawagattegama"
          ,"Pallama"
          ,"Puttalam"
          ,"Vanathavilluwa"
          ,"Wennappuwa"
          ,"Aranayaka"
          ,"Bulathkohupitiya"
          ,"Dehiovita"
          ,"Deraniyagala"
          ,"Galigamuwa"
          ,"Kegalle"
          ,"Mawanella"
          ,"Rambukkana"
          ,"Ruwanwella"
          ,"Warakapola"
          ,"Yatiyanthota"
          ,"Ayagama"
          ,"Balangoda"
          ,"Eheliyagoda"
          ,"Elapattha"
          ,"Embilipitiya"
          ,"Godakawela"
          ,"Imbulpe"
          ,"Kahawatta"
          ,"Kalawana"
          ,"Kiriella"
          ,"Kolonna"
          ,"Kuruvita"
          ,"Nivithigala"
          ,"Opanayaka"
          ,"Pelmadulla"
          ,"Ratnapura"
          ,"Weligepola"
          ,"Akmeemana"
          ,"Ambalangoda"
          ,"Baddegama"
          ,"Balapitiya"
          ,"Benthota"
          ,"Bope-Poddala"
          ,"Elpitiya"
          ,"Galle"
          ,"Gonapinuwala"
          ,"Habaraduwa"
          ,"Hikkaduwa"
          ,"Imaduwa"
          ,"Karandeniya"
          ,"Nagoda"
          ,"Neluwa"
          ,"Niyagama"
          ,"Thawalama"
          ,"Welivitiya-Divithura"
          ,"Yakkalamulla"
          ,"Ambalantota"
          ,"Angunakolapelessa"
          ,"Beliatta"
          ,"Hambantota"
          ,"Katuwana"
          ,"Lunugamvehera"
          ,"Okewela"
          ,"Sooriyawewa"
          ,"Tangalle"
          ,"Thissamaharama"
          ,"Walasmulla"
          ,"Weeraketiya"
          ,"Akuressa"
          ,"Athuraliya"
          ,"Devinuwara"
          ,"Dickwella"
          ,"Hakmana"
          ,"Kamburupitiya"
          ,"Kirinda Puhulwella"
          ,"Kotapola"
          ,"Malimbada"
          ,"Matara"
          ,"Mulatiyana"
          ,"Pasgoda"
          ,"Pitabeddara"
          ,"Thihagoda"
          ,"Weligama"
          ,"Welipitiya"
          ,"Badulla"
          ,"Bandarawela"
          ,"Ella"
          ,"Haldummulla"
          ,"Hali-Ela"
          ,"Haputale"
          ,"Kandaketiya"
          ,"Lunugala"
          ,"Mahiyanganaya"
          ,"Meegahakivula"
          ,"Passara"
          ,"Rideemaliyadda"
          ,"Soranathota"
          ,"Uva-Paranagama"
          ,"Welimada"
          ,"Badalkumbura"
          ,"Bibile"
          ,"Buttala"
          ,"Katharagama"
          ,"Madulla"
          ,"Medagama"
          ,"Moneragala"
          ,"Sevanagala"
          ,"Siyambalanduwa"
          ,"Thanamalvila"
          ,"Wellawaya"
          ,"Colombo"
          ,"Dehiwala"
          ,"Homagama"
          ,"Kaduwela"
          ,"Kesbewa"
          ,"Kolonnawa"
          ,"Kotte"
          ,"Maharagama"
          ,"Moratuwa"
          ,"Padukka"
          ,"Ratmalana"
          ,"Seethawaka"
          ,"Thimbirigasyaya"
          ,"Attanagalla"
          ,"Biyagama"
          ,"Divulapitiya"
          ,"Dompe"
          ,"Gampaha"
          ,"Ja-Ela"
          ,"Katana"
          ,"Kelaniya"
          ,"Mahara"
          ,"Minuwangoda"
          ,"Mirigama"
          ,"Negombo"
          ,"Wattala"
          ,"Agalawatta"
          ,"Bandaragama"
          ,"Beruwala"
          ,"Bulathsinhala"
          ,"Dodangoda"
          ,"Horana"
          ,"Ingiriya"
          ,"Kalutara"
          ,"Madurawela"
          ,"Mathugama"
          ,"Millaniya"
          ,"Palindanuwara"
          ,"Panadura"
          ,"Walallavita"],    
  },
  regVoteCount: {
    type: Number,
    required: true,
  },
  currentVoteCount: {
    type: Number,
    default: 0,
  },
  publicKeyPath: {
    type: String,
    unique: true,
  },
  districtID: {
    type: mongoose.Schema.Types.ObjectId,
    unique: false,
    ref: "District",
    required: true,
  },
});

const Division = mongoose.model("Division", divisionSchema);

exports.Division = Division;
